name: ADVENTJS

on:
  push:
    paths:
    - './adventjs/**'
    - '.github/workflows/adventjs.yml'
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

defaults:
  run:
    working-directory: ./adventjs

jobs:
  linter:
    name: âœ… Validate linter
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v3

      - name: ğŸŸ¢ Setup NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: './adventjs/package-lock.json'

      - name: ğŸ“¥ Install dependencies
        run: npm ci

      - name: ğŸ“‘ Check lint
        run: npm run lint

  test:
    name: ğŸ§‘â€ğŸ”¬ Test project
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v3

      - name: ğŸŸ¢ Setup NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: './adventjs/package-lock.json'

      - name: ğŸ“¥ Install dependencies
        run: npm ci

      - name: ğŸ§ª Run challenges
        run: npm run test